### PR TITLE
PR for some boiler-plate updates - Update/python scratch

### PR DESCRIPTION
**Pull request by ayjayt**
This pull request will:

Update their (covidclinicaldata's) repository
Integrate the covidclinicaldata teams python into ours

~Also, note, I remove my write permissions to the submodule after updating it so that jupyter doesn't mess around with it.~

^ That doesn't work

**TODO**:

Maybe do some examples with scikit or something. Kmapper.
Beef up Oliver's normalization
Create a rudimentary metric

### CODE REVIEW

**Comment by ayjayt** [comment]
Hey @shpew12 if you run `print(columns)` in your `normalize` function, you'll see that the correct parameter to pass to apply is `index` and not `columns` (I think you'll agree?), but also notice that it seems to print out the first column twice? Is that because one of these things is somehow acting as a primary key? Not sure. Would like your help here.

**Review by oliverchubet — CHANGES_REQUESTED** [review]
Why is it asking me to install matplotlib and seaborn libs?
I can't find where the dependency is pulled in.
Other than that, looks good.
You should get rid of the scratch work if you don't need it.
Also, the fact that you're only doing head(100), you miss a unique value in one of the columns. 'Critical'
I suggest changing the replace values
Moderate: .33
Severe: .66
Critical: 1

**Comment by ayjayt** [comment]
The next pull request addresses the actual normalization. This was just some boiler plate on top of your original work to pull in the upstream (carbon health) libraries.

The scratch work is also deleted in the next pull request.

The next pull request actually uses the matplotlib and seaborn, which probs came from the upstream dependency. Not happy w/ python's graphing facilities. Bokeh looks better but concerned that generating a png graph requires a whole webkit instance. Seems heavy.

Do you need me to make these changes now? I'd rather move on to the next PR because merging/diffing ipynb files is a pain.

**Comment by ayjayt** [comment]
Oh and besides my above comment @shpew12 the reason I used head(100) is because, as you noticed, the supplied normalizing code (yours) didn't support the entire data set, only a portion. I just didn't want to address any normilization/santitization for another PR.

I mean the focus of this PR to be dependencies, how they are discovered, and how they are pulled in.

One problem with this is that it only searches lower for the root directory, not higher. It shouldn't be an issue in practice but w/e.

**Pull request merged**
