### PR TITLE
PR 2 (go through other one first) Normalize- Everything 0 to 1. Update/sanitize

### PR DESCRIPTION
**Pull request by ayjayt**
Some creative liberties were taken. Includes many graphs/info about data. Please enjoy. @shpew12 

edit:
Sorry, I didn't explain this PR well. I think I was tired.

This 

a) provides data analysis functions

b) removes non-sense data
* columns are not completely orthogonal, so they are tested against each other
* columns with nonsense values (negative ages) are just removed

c) fills in missing data meaningful
* if a test wasn't conducted, we assume the physician decided that no indication meant no test was necessary, and that values were likely normal from appearance. ie, negative test, normal vitals by age.

d) normalize everything from 0-1

### CODE REVIEW

**Review by oliverchubet — CHANGES_REQUESTED** [review]
When I run the cell with df.apply(analyze_column ... blah blah ...
I get AttributeError: 'bool' object has no attribute 'sum'
I don't really know what you're trying to do in this PR. I liked the other one better.

**Comment by ayjayt** [comment]
OMG

**Comment by ayjayt** [comment]
This one fixes SO much more in the data @shpew12 . ~It removes nonsense values, fills in missing data with sensible values (not necessarily averages). Removes rows/columns if it needs to.~ I edited the PR description


What cell are you actually trying to run that you get an error on, please? That function is called twice.

**Comment by ayjayt** [comment]
> When I run the cell with df.apply(analyze_column ... blah blah ...
> I get AttributeError: 'bool' object has no attribute 'sum'

@shpew12 actually, one of the problems is that we only maintain one data object- not a "original" and "normalized", and sometimes running cells in different orders can deliver data that the normalization functions don't expect.

Furthermore, these loops I find hard to debug (what values exactly did you choke on?) and the typing in python is a hassle.

**Comment by oliverchubet** [comment]
> > When I run the cell with df.apply(analyze_column ... blah blah ...
> > I get AttributeError: 'bool' object has no attribute 'sum'
> 
> @shpew12 actually, one of the problems is that we only maintain one data object- not a "original" and "normalized", and sometimes running cells in different orders can deliver data that the normalization functions don't expect.
> 
> Furthermore, these loops I find hard to debug (what values exactly did you choke on?) and the typing in python is a hassle.

I think we should have self-contained cells. Like, you run them top down to get everything in the namespace, but then have self-contained unit tests. Or maybe unit tests in another notebook. If you were writing python out of a jupyter notebook you wouldn't have things all mixed together like they are. Let me know what you think, but I'm in favor of refactoring it. Then we won't have to address these questions.

**Comment by ayjayt** [comment]
I mean I am more or less for this like, jupyter is cool or w/e but I would much prefer to write regular python. I have no idea how to make jupyter notebooks like real python.

Should we be collaboing on real python and then just be making notebooks at the end? @shpew12.

But also I want to address this bug you're having.

**Comment by oliverchubet** [comment]
> I mean I am more or less for this like, jupyter is cool or w/e but I would much prefer to write regular python. I have no idea how to make jupyter notebooks like real python.
> 
> Should we be collaboing on real python and then just be making notebooks at the end? @shpew12.
> 
> But also I want to address this bug you're having.

Yeah, just separate it, like everything in one notebook be as if it was in 1 file in python and you can probably import it. Then just have a separate file for unit tests.

**Pull request merged**
